In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a.shape   ## row vector

(5,)

In [4]:
b = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
            ])

In [5]:
b.shape    # this is a 3 X 3 matrix

(3, 3)

In [7]:
c = b.reshape(9,1)

In [8]:
c.shape

(9, 1)

In [9]:
c   ## is column vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [12]:
c.T   ## row vector 

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
a = np.array([1, 2])

In [28]:
d = np.arange(18).reshape(3,3,2)

In [29]:
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])